### ISSUE TITLE
[Idea] Scoreboard Team Sidebar Image-Json Viewer

### ISSUE THREAD

**Issue by centuralus** [CloudWolfYT/cloudwolfyt.github.io#4]
The idea is to expand the conditions on the radio buttons to include another option for a Scoreboard Objective Sidebar View of the video;

I plan to implement this by setting up a single team to view the video and 15 teams for each line of that video scoreboard. (Each labels from 0-15 or 0-e not sure)

The 15 team have a suffix of that line/frame of the video (Which updates each tick similar to the other videos)

We hardcode the names 0-e or 0-15 each to their own respected team/line-frame (The suffix now is attached to that hardcoded player)

Finally we add a score of 0 for each of these (Or whatever number I suppose between 0-9) to add them to our video sidebar display.

**Possible Drawbacks**
We should Assume the max width is 46 Pixels UNLESS we are to ask the player to change GUI settings.
Height limitation is 15 due to scoreboard objective sidebar max view is 15 different players/entity objectives.
Restricts usage of one of the team scoreboard colors (Unless a way to display a sidebar for a specific team has been added)

**Future Use-case**
-If Mojang ever added clickEvent functionality to the sidebar view we could make interfaces there
-Perhaps use Pitch and Yaw to determine Panoramic Images/Videos; This way the 15 lines is not limited given we could shift the view of the image based on their rotation.
-General Overlaying Animation; With the Overflow you could assume a very Large screen then run animations across the screen (And even leave items transparent so the user can still interact with the playing field of view) Though without GUI detection this would have a cavet when a user has turned off transparency.

**Comment by CloudWolfYT** [comment]
I like the idea but the problem is that you cannot have multi-colored names in scoreboard sidebars. If you put an entity on a scoreboard the name will not have the coloration that u see in game, and teams can only change name colors to 1 static color, so each line of the video would only be allowed to be 1 color

**Comment by centuralus** [comment]
I have a prototype working atm they might have changed it in 1.17 snapshots.

**Comment by centuralus** [comment]
Sorry if I did not explain correctly; We are using the Prefix of a team and Hardcoded players 0-e (0,1,2,3,4,5,6,7,8,9,a,b,c,d,e) as the entity name who is joined to a matching team each with a prefix Array of extract_data(data,end_length,start_point)
 (Which perhaps did not work in old version but as of 21w08b it does allow multiple colors and text array items in the prefix of a team)
